In [1]:
print("Hello World")

Hello World

In [2]:
!pip list

Package                      Version
---------------------------- ------------
absl-py                      2.1.0
alembic                      1.13.1
asttokens                    2.4.1
astunparse                   1.6.3
cachetools                   5.3.2
catboost                     1.2.3
certifi                      2024.2.2
charset-normalizer           3.3.2
colorlog                     6.8.2
comm                         0.2.1
contourpy                    1.2.0
cycler                       0.12.1
debugpy                      1.8.1
decorator                    5.1.1
et-xmlfile                   1.1.0
executing                    2.0.1
filelock                     3.13.1
flatbuffers                  23.5.26
fonttools                    4.49.0
fsspec                       2024.2.0
gast                         0.5.4
google-auth                  2.28.1
google-auth-oauthlib         1.2.0
google-pasta                 0.2.0
graphviz                     0.20.1
greenlet                     3.0.3
grpcio                       1.62.0
h5py                         3.10.0
idna                         3.6
ipykernel                    6.29.2
ipython                      8.22.1
jedi                         0.19.1
Jinja2                       3.1.3
joblib                       1.3.2
jupyter_client               8.6.0
jupyter_core                 5.7.1
keras                        2.15.0
kiwisolver                   1.4.5
libclang                     16.0.6
lightgbm                     4.3.0
Mako                         1.3.2
Markdown                     3.5.2
MarkupSafe                   2.1.5
matplotlib                   3.8.3
matplotlib-inline            0.1.6
ml-dtypes                    0.2.0
mpmath                       1.3.0
nest-asyncio                 1.6.0
networkx                     3.2.1
numpy                        1.26.4
nvidia-cublas-cu12           12.1.3.1
nvidia-cuda-cupti-cu12       12.1.105
nvidia-cuda-nvrtc-cu12       12.1.105
nvidia-cuda-runtime-cu12     12.1.105
nvidia-cudnn-cu12            8.9.2.26
nvidia-cufft-cu12            11.0.2.54
nvidia-curand-cu12           10.3.2.106
nvidia-cusolver-cu12         11.4.5.107
nvidia-cusparse-cu12         12.1.0.106
nvidia-nccl-cu12             2.19.3
nvidia-nvjitlink-cu12        12.3.101
nvidia-nvtx-cu12             12.1.105
oauthlib                     3.2.2
openpyxl                     3.1.2
opt-einsum                   3.3.0
optuna                       3.5.0
packaging                    23.2
pandas                       2.2.1
parso                        0.8.3
pexpect                      4.9.0
pillow                       10.2.0
pip                          24.0
platformdirs                 4.2.0
plotly                       5.19.0
prompt-toolkit               3.0.43
protobuf                     4.25.3
psutil                       5.9.8
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyasn1                       0.5.1
pyasn1-modules               0.3.0
Pygments                     2.17.2
pyparsing                    3.1.1
python-dateutil              2.8.2
pytz                         2024.1
PyYAML                       6.0.1
pyzmq                        25.1.2
requests                     2.31.0
requests-oauthlib            1.3.1
rsa                          4.9
scikit-learn                 1.4.1.post1
scipy                        1.12.0
seaborn                      0.13.2
setuptools                   68.1.2
six                          1.16.0
SQLAlchemy                   2.0.27
stack-data                   0.6.3
sympy                        1.12
tenacity                     8.2.3
tensorboard                  2.15.2
tensorboard-data-server      0.7.2
tensorflow                   2.15.0.post1
tensorflow-estimator         2.15.0
tensorflow-io-gcs-filesystem 0.36.0
termcolor                    2.4.0
threadpoolctl                3.3.0
torch                        2.2.1
torchvision                  0.17.1
tornado                      6.4
tqdm                         4.66.2
traitlets                    5.14.1
triton                       2.2.0
typing_extensions            4.9.0
tzdata                       2024.1
urllib3                      2.2.1
wcwidth                      0.2.13
Werkzeug                     3.0.1
wheel                        0.42.0
wrapt                        1.14.1
xgboost                      2.0.3

In [3]:
!pip install pandas numpy matplotlib seaborn scikit-learn xgboost lightgbm catboost optuna tensorflow keras torch torchvision

Requirement already satisfied: pandas in ./.venv/lib/python3.11/site-packages (2.2.1)
Requirement already satisfied: numpy in ./.venv/lib/python3.11/site-packages (1.26.4)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.11/site-packages (3.8.3)
Requirement already satisfied: seaborn in ./.venv/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.11/site-packages (1.4.1.post1)
Requirement already satisfied: xgboost in ./.venv/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: lightgbm in ./.venv/lib/python3.11/site-packages (4.3.0)
Requirement already satisfied: catboost in ./.venv/lib/python3.11/site-packages (1.2.3)
Requirement already satisfied: optuna in ./.venv/lib/python3.11/site-packages (3.5.0)
Requirement already satisfied: tensorflow in ./.venv/lib/python3.11/site-packages (2.15.0.post1)
Requirement already satisfied: keras in ./.venv/lib/python3.11/site-packages (2.15.0)
Requirement already satisfied: torch in ./.venv/lib/python3.11/site-packages (2.2.1)
Requirement already satisfied: torchvision in ./.venv/lib/python3.11/site-packages (0.17.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.11/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.11/site-packages (from matplotlib) (4.49.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.11/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.11/site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.11/site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./.venv/lib/python3.11/site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: scipy>=1.6.0 in ./.venv/lib/python3.11/site-packages (from scikit-learn) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in ./.venv/lib/python3.11/site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.venv/lib/python3.11/site-packages (from scikit-learn) (3.3.0)
Requirement already satisfied: graphviz in ./.venv/lib/python3.11/site-packages (from catboost) (0.20.1)
Requirement already satisfied: plotly in ./.venv/lib/python3.11/site-packages (from catboost) (5.19.0)
Requirement already satisfied: six in ./.venv/lib/python3.11/site-packages (from catboost) (1.16.0)
Requirement already satisfied: alembic>=1.5.0 in ./.venv/lib/python3.11/site-packages (from optuna) (1.13.1)
Requirement already satisfied: colorlog in ./.venv/lib/python3.11/site-packages (from optuna) (6.8.2)
Requirement already satisfied: sqlalchemy>=1.3.0 in ./.venv/lib/python3.11/site-packages (from optuna) (2.0.27)
Requirement already satisfied: tqdm in ./.venv/lib/python3.11/site-packages (from optuna) (4.66.2)
Requirement already satisfied: PyYAML in ./.venv/lib/python3.11/site-packages (from optuna) (6.0.1)
Requirement already satisfied: absl-py>=1.0.0 in ./.venv/lib/python3.11/site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in ./.venv/lib/python3.11/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in ./.venv/lib/python3.11/site-packages (from tensorflow) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in ./.venv/lib/python3.11/site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in ./.venv/lib/python3.11/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in ./.venv/lib/python3.11/site-packages (from tensorflow) (3.10.0)
Requirement already satisfied: libclang>=13.0.0 in ./.venv/lib/python3.11/site-packages (from tensorflow) (16.0.6)
Requirement already satisfied: ml-dtypes~=0.2.0 in ./.venv/lib/python3.11/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in ./.venv/lib/python3.11/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in ./.venv/lib/python3.11/site-packages (from tensorflow) (4.25.3)
Requirement already satisfied: setuptools in ./.venv/lib/python3.11/site-packages (from tensorflow) (68.1.2)
Requirement already satisfied: termcolor>=1.1.0 in ./.venv/lib/python3.11/site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in ./.venv/lib/python3.11/site-packages (from tensorflow) (4.9.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in ./.venv/lib/python3.11/site-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in ./.venv/lib/python3.11/site-packages (from tensorflow) (0.36.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./.venv/lib/python3.11/site-packages (from tensorflow) (1.62.0)
Requirement already satisfied: tensorboard<2.16,>=2.15 in ./.venv/lib/python3.11/site-packages (from tensorflow) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in ./.venv/lib/python3.11/site-packages (from tensorflow) (2.15.0)
Requirement already satisfied: filelock in ./.venv/lib/python3.11/site-packages (from torch) (3.13.1)
Requirement already satisfied: sympy in ./.venv/lib/python3.11/site-packages (from torch) (1.12)
Requirement already satisfied: networkx in ./.venv/lib/python3.11/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.11/site-packages (from torch) (3.1.3)
Requirement already satisfied: fsspec in ./.venv/lib/python3.11/site-packages (from torch) (2024.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in ./.venv/lib/python3.11/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in ./.venv/lib/python3.11/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in ./.venv/lib/python3.11/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in ./.venv/lib/python3.11/site-packages (from torch) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in ./.venv/lib/python3.11/site-packages (from torch) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in ./.venv/lib/python3.11/site-packages (from torch) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in ./.venv/lib/python3.11/site-packages (from torch) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in ./.venv/lib/python3.11/site-packages (from torch) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in ./.venv/lib/python3.11/site-packages (from torch) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in ./.venv/lib/python3.11/site-packages (from torch) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in ./.venv/lib/python3.11/site-packages (from torch) (12.1.105)
Requirement already satisfied: triton==2.2.0 in ./.venv/lib/python3.11/site-packages (from torch) (2.2.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in ./.venv/lib/python3.11/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.3.101)
Requirement already satisfied: Mako in ./.venv/lib/python3.11/site-packages (from alembic>=1.5.0->optuna) (1.3.2)
Requirement already satisfied: wheel<1.0,>=0.23.0 in ./.venv/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow) (0.42.0)
Requirement already satisfied: greenlet!=0.4.17 in ./.venv/lib/python3.11/site-packages (from sqlalchemy>=1.3.0->optuna) (3.0.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in ./.venv/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.28.1)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in ./.venv/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in ./.venv/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.5.2)
Requirement already satisfied: requests<3,>=2.21.0 in ./.venv/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in ./.venv/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in ./.venv/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.11/site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: tenacity>=6.2.0 in ./.venv/lib/python3.11/site-packages (from plotly->catboost) (8.2.3)
Requirement already satisfied: mpmath>=0.19 in ./.venv/lib/python3.11/site-packages (from sympy->torch) (1.3.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.venv/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.venv/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in ./.venv/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.venv/lib/python3.11/site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2024.2.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in ./.venv/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in ./.venv/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (3.2.2)

In [4]:
!pip install openpyxl

Requirement already satisfied: openpyxl in ./.venv/lib/python3.11/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in ./.venv/lib/python3.11/site-packages (from openpyxl) (1.1.0)

In [5]:
import pandas as pd

df = pd.read_excel("RADMS SAMPLE DATA.xlsx")
df.head()

,2017,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,DISTRICT,POLICE STATION,PS STRENGTH,FIR NO,DATE,DAY,ACCIDENT TYPE,TIME,MINETUES,WEATHER CONDITION,VEHICLE TYPE,COLLITION TYPE,ROAD TYPE,DRIVER NAME,DRIVER AGE,PASSENGER NAME,PASSENGER AGE,PEDESTRIAN NAME,PEDESTRIAN AGE
1,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00005/2017,2017-01-08 00:00:00,Sunday,FATAL,20,30,FINE,UNKNOWN VEHICLE,HIT FROM REAR,STATE HIGHWAY,Not applicable,0,NaN,NaN,NaN,NaN
2,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00010/2017,2017-01-18 00:00:00,Wednesday,FATAL,11,30,FINE,BUS,HEAD ON,STATE HIGHWAY,Krishnamoorthy,50,Vishwanathan,45,NaN,NaN
3,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00014/2017,2017-01-24 00:00:00,Tuesday,SIMPLE INJURY (HOSPITALISED),11,0,FINE,MOTOR CYCLE,HIT PEDESTRIAN,STATE HIGHWAY,MANIKANDAN,30,NaN,NaN,BHARATHIDHASAN,34
4,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00015/2017,2017-01-15 00:00:00,Sunday,FATAL,10,30,FINE,MOPED,HIT FROM REAR,STATE HIGHWAY,VENGATAPATHI RAJ,30,NaN,NaN,RAMASAMY,70

It seems that on linux, if excel spreadsheets don't act so well. Microsoft office does not exist on this platform for obvious reasons and open source Libre Office (which comes with Ubuntu by default) does not seem to handle them well
Instead, I've used Windows to convert the XSLX to a CSV file. We will be using the CSV file in this notebook.

In [6]:
df = pd.read_csv("RADMS SAMPLE DATA.csv")
df.head()

,DISTRICT,POLICE STATION,PS STRENGTH,FIR NO,DATE,DAY,ACCIDENT TYPE,TIME,MINETUES,WEATHER CONDITION,VEHICLE TYPE,COLLITION TYPE,ROAD TYPE,DRIVER NAME,DRIVER AGE,PASSENGER NAME,PASSENGER AGE,PEDESTRIAN NAME,PEDESTRIAN AGE
0,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00005/2017,1/8/2017,Sunday,FATAL,20,30,FINE,UNKNOWN VEHICLE,HIT FROM REAR,STATE HIGHWAY,Not applicable,0,NaN,NaN,NaN,NaN
1,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00010/2017,1/18/2017,Wednesday,FATAL,11,30,FINE,BUS,HEAD ON,STATE HIGHWAY,Krishnamoorthy,50,Vishwanathan,45.0,NaN,NaN
2,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00014/2017,1/24/2017,Tuesday,SIMPLE INJURY (HOSPITALISED),11,0,FINE,MOTOR CYCLE,HIT PEDESTRIAN,STATE HIGHWAY,MANIKANDAN,30,NaN,NaN,BHARATHIDHASAN,34.0
3,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00015/2017,1/15/2017,Sunday,FATAL,10,30,FINE,MOPED,HIT FROM REAR,STATE HIGHWAY,VENGATAPATHI RAJ,30,NaN,NaN,RAMASAMY,70.0
4,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00018/2017,1/26/2017,Thursday,SIMPLE INJURY (HOSPITALISED),16,15,FINE,CAR LMV,HIT FROM REAR,STATE HIGHWAY,Sivasankaran,45,NaN,NaN,NaN,NaN

In [7]:
df.columns

Index(['DISTRICT', 'POLICE STATION', 'PS STRENGTH', 'FIR NO', 'DATE', 'DAY',
       'ACCIDENT TYPE', 'TIME', 'MINETUES', 'WEATHER CONDITION',
       'VEHICLE TYPE', 'COLLITION TYPE', 'ROAD TYPE', 'DRIVER NAME',
       'DRIVER AGE', 'PASSENGER NAME', 'PASSENGER AGE', 'PEDESTRIAN NAME',
       'PEDESTRIAN AGE'],
      dtype='object')

In [8]:
df.describe()

,PS STRENGTH,TIME,MINETUES,DRIVER AGE,PASSENGER AGE,PEDESTRIAN AGE
count,62859.000000,62859.000000,62859.000000,62859.000000,16883.000000,17383.000000
mean,41.558218,14.118010,19.478849,33.969312,34.676953,47.464764
std,17.690028,5.500819,16.863420,15.044527,17.162789,20.631920
min,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,10.000000,0.000000,25.000000,23.000000,35.000000
50%,36.000000,15.000000,25.000000,34.000000,33.000000,50.000000
75%,50.000000,19.000000,30.000000,42.000000,45.000000,60.000000
max,110.000000,23.000000,59.000000,540.000000,654.000000,688.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62859 entries, 0 to 62858
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   DISTRICT           62859 non-null  object
 1   POLICE STATION     62859 non-null  object
 2   PS STRENGTH        62859 non-null  int64
 3   FIR NO             62859 non-null  object
 4   DATE               62859 non-null  object
 5   DAY                62859 non-null  object
 6   ACCIDENT TYPE      62859 non-null  object
 7   TIME               62859 non-null  int64
 8   MINETUES           62859 non-null  int64
 9   WEATHER CONDITION  62859 non-null  object
 10  VEHICLE TYPE       62859 non-null  object
 11  COLLITION TYPE     62859 non-null  object
 12  ROAD TYPE          62859 non-null  object
 13  DRIVER NAME        62837 non-null  object
 14  DRIVER AGE         62859 non-null  int64
 15  PASSENGER NAME     16883 non-null  object
 16  PASSENGER AGE      16883 non-null  float64
 17  PEDESTRIAN NAME    17380 non-null  object
 18  PEDESTRIAN AGE     17383 non-null  float64
dtypes: float64(2), int64(4), object(13)
memory usage: 9.1+ MB

In [10]:
df.isnull().sum()

DISTRICT                 0
POLICE STATION           0
PS STRENGTH              0
FIR NO                   0
DATE                     0
DAY                      0
ACCIDENT TYPE            0
TIME                     0
MINETUES                 0
WEATHER CONDITION        0
VEHICLE TYPE             0
COLLITION TYPE           0
ROAD TYPE                0
DRIVER NAME             22
DRIVER AGE               0
PASSENGER NAME       45976
PASSENGER AGE        45976
PEDESTRIAN NAME      45479
PEDESTRIAN AGE       45476
dtype: int64

The passenger name age, pedestrian name and pedestrian age are not really that important, and considering the huge amount of null values present in all of them, I don't think we will really lose that much if we drop all of them

In [11]:
df = df.drop(columns=['PASSENGER NAME', 'PASSENGER AGE', 'PEDESTRIAN NAME', 'PEDESTRIAN AGE'])

Now, Let's try and convert the time from their time and hours into something standard. I'm not sure if models will work better with string data or with datetime data, so I will convert into both and see how they perform

In [12]:
import pandas as pd
from datetime import datetime, timedelta

time_of_day = df.apply(lambda row: timedelta(hours=int(row['TIME']), minutes=int(row['MINETUES'])), axis=1)

# Convert each timedelta into a datetime.time object
df['24_HOUR_TIME'] = time_of_day.apply(lambda x: (datetime.min + x).time())

# Also converting it into a string for future use
df['24_HOUR_TIME_STR'] = df['24_HOUR_TIME'].apply(lambda x: x.strftime('%H:%M'))

# Display the DataFrame to verify the new column
print(df[['TIME', 'MINETUES', '24_HOUR_TIME', '24_HOUR_TIME_STR']].head())

   TIME  MINETUES 24_HOUR_TIME 24_HOUR_TIME_STR
0    20        30     20:30:00            20:30
1    11        30     11:30:00            11:30
2    11         0     11:00:00            11:00
3    10        30     10:30:00            10:30
4    16        15     16:15:00            16:15

I don't think we need the time and minetues(minutes) columns, as they are already represented in the time column. I will drop them as well

In [13]:
df.drop(columns=['TIME', 'MINETUES'], inplace=True)
df.head()

,DISTRICT,POLICE STATION,PS STRENGTH,FIR NO,DATE,DAY,ACCIDENT TYPE,WEATHER CONDITION,VEHICLE TYPE,COLLITION TYPE,ROAD TYPE,DRIVER NAME,DRIVER AGE,24_HOUR_TIME,24_HOUR_TIME_STR
0,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00005/2017,1/8/2017,Sunday,FATAL,FINE,UNKNOWN VEHICLE,HIT FROM REAR,STATE HIGHWAY,Not applicable,0,20:30:00,20:30
1,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00010/2017,1/18/2017,Wednesday,FATAL,FINE,BUS,HEAD ON,STATE HIGHWAY,Krishnamoorthy,50,11:30:00,11:30
2,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00014/2017,1/24/2017,Tuesday,SIMPLE INJURY (HOSPITALISED),FINE,MOTOR CYCLE,HIT PEDESTRIAN,STATE HIGHWAY,MANIKANDAN,30,11:00:00,11:00
3,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00015/2017,1/15/2017,Sunday,FATAL,FINE,MOPED,HIT FROM REAR,STATE HIGHWAY,VENGATAPATHI RAJ,30,10:30:00,10:30
4,ARIYALUR,ANDIMADAM,50,ALR/ANDIA/00018/2017,1/26/2017,Thursday,SIMPLE INJURY (HOSPITALISED),FINE,CAR LMV,HIT FROM REAR,STATE HIGHWAY,Sivasankaran,45,16:15:00,16:15

Once again, I don't think we need Police Station Strength as well as FIR NO, so let's drop them
Simulataneously, I also want to find out the unique values for each of the columns so we can decide what we can encode and what we should keep as it is

In [14]:
# Drop 'FIR NO' and 'PS STRENGTH' columns
df = df.drop(['FIR NO', 'PS STRENGTH'], axis=1)

# Display the DataFrame to verify columns are dropped
print(df.head())

   DISTRICT POLICE STATION       DATE        DAY  \
0  ARIYALUR      ANDIMADAM   1/8/2017  Sunday
1  ARIYALUR      ANDIMADAM  1/18/2017  Wednesday
2  ARIYALUR      ANDIMADAM  1/24/2017  Tuesday
3  ARIYALUR      ANDIMADAM  1/15/2017  Sunday
4  ARIYALUR      ANDIMADAM  1/26/2017  Thursday

                  ACCIDENT TYPE WEATHER CONDITION     VEHICLE TYPE  \
0                         FATAL              FINE  UNKNOWN VEHICLE
1                         FATAL              FINE              BUS
2  SIMPLE INJURY (HOSPITALISED)              FINE      MOTOR CYCLE
3                         FATAL              FINE            MOPED
4  SIMPLE INJURY (HOSPITALISED)              FINE          CAR LMV

   COLLITION TYPE      ROAD TYPE       DRIVER NAME  DRIVER AGE 24_HOUR_TIME  \
0   HIT FROM REAR  STATE HIGHWAY    Not applicable           0     20:30:00
1         HEAD ON  STATE HIGHWAY    Krishnamoorthy          50     11:30:00
2  HIT PEDESTRIAN  STATE HIGHWAY        MANIKANDAN          30     11:00:00
3   HIT FROM REAR  STATE HIGHWAY  VENGATAPATHI RAJ          30     10:30:00
4   HIT FROM REAR  STATE HIGHWAY      Sivasankaran          45     16:15:00

  24_HOUR_TIME_STR
0            20:30
1            11:30
2            11:00
3            10:30
4            16:15

In [15]:
# Find and print unique values for each column
for column in df.columns:
    unique_values = df[column].unique()
    print(f"Unique values in '{column}': {unique_values}\n")

Unique values in 'DISTRICT': ['ARIYALUR' 'COIMBATORE' 'COIMBATORE CITY' 'CHENNAI CITY' 'CHENNAI'
 'CUDDALORE' 'DINDIGUL' 'DHARMAPURI' 'ERODE' 'KANYAKUMARI' 'KANCHEEPURAM'
 'KRISHNAGIRI' 'KARUR' 'MADURAI' 'MADURAI CITY' 'NAGAPATTINAM' 'NILGIRIS'
 'NAMAKKAL' 'PERAMBALUR' 'PUDUKKOTTAI' 'RAMANATHAPURAM' 'SALEM'
 'SALEM CITY' 'SIVAGANGAI' 'THANJAVUR' 'TIRUNELVELI' 'TIRUNELVELI CITY'
 'THENI' 'TIRUPPUR CITY' 'TRICHY' 'TRICHY CITY' 'TUTICORIN' 'THIRUVALLUR'
 'THIRUVANNAMALAI' 'TIRUVARUR' 'VELLORE' 'VIRUDHUNAGAR' 'VILLUPURAM'
 'TIRUPPUR']

Unique values in 'POLICE STATION': ['ANDIMADAM' 'ARIYALUR' 'IRUMBULIKURICHI' ... 'Uthukuzhi' 'Vellakoil'
 'amaravathy']

Unique values in 'DATE': ['1/8/2017' '1/18/2017' '1/24/2017' '1/15/2017' '1/26/2017' '2/7/2017'
 '2/9/2017' '2/19/2017' '2/23/2017' '3/4/2017' '3/11/2017' '3/19/2017'
 '3/27/2017' '3/29/2017' '4/10/2017' '4/16/2017' '4/15/2017' '4/17/2017'
 '4/26/2017' '3/30/2017' '4/28/2017' '4/30/2017' '5/1/2017' '5/6/2017'
 '5/9/2017' '5/13/2017' '5/14/2017' '5/25/2017' '5/26/2017' '5/27/2017'
 '5/28/2017' '7/13/2017' '6/2/2017' '6/7/2017' '6/14/2017' '6/23/2017'
 '6/28/2017' '7/20/2017' '7/19/2017' '7/28/2017' '8/7/2017' '8/18/2017'
 '8/20/2017' '8/17/2017' '8/21/2017' '8/26/2017' '8/27/2017' '9/2/2017'
 '9/7/2017' '9/17/2017' '9/26/2017' '10/1/2017' '10/16/2017' '10/21/2017'
 '10/20/2017' '10/27/2017' '11/4/2017' '11/9/2017' '11/15/2017'
 '11/17/2017' '11/22/2017' '11/25/2017' '12/11/2017' '11/30/2017'
 '12/2/2017' '12/24/2017' '12/20/2017' '12/31/2017' '1/5/2017' '1/2/2017'
 '1/22/2017' '1/29/2017' '2/8/2017' '1/27/2017' '2/21/2017' '2/24/2017'
 '2/26/2017' '3/13/2017' '3/16/2017' '3/20/2017' '3/12/2017' '4/6/2017'
 '4/8/2017' '4/19/2017' '4/29/2017' '5/17/2017' '5/16/2017' '5/21/2017'
 '5/22/2017' '6/6/2017' '6/10/2017' '6/18/2017' '10/14/2017' '6/27/2017'
 '6/29/2017' '7/14/2017' '7/16/2017' '7/18/2017' '7/22/2017' '7/24/2017'
 '8/2/2017' '7/31/2017' '7/25/2017' '8/4/2017' '8/9/2017' '8/12/2017'
 '8/24/2017' '9/9/2017' '9/12/2017' '9/16/2017' '9/19/2017' '9/30/2017'
 '10/2/2017' '10/4/2017' '10/6/2017' '10/8/2017' '10/13/2017' '10/18/2017'
 '10/23/2017' '10/24/2017' '11/3/2017' '10/31/2017' '11/21/2017'
 '11/23/2017' '11/29/2017' '12/1/2017' '12/10/2017' '12/14/2017'
 '2/13/2017' '4/5/2017' '6/5/2017' '7/11/2017' '7/10/2017' '8/1/2017'
 '9/3/2017' '9/10/2017' '1/4/2017' '12/29/2017' '1/16/2017' '1/17/2017'
 '1/20/2017' '1/23/2017' '1/25/2017' '1/30/2017' '2/3/2017' '2/15/2017'
 '2/20/2017' '2/25/2017' '3/10/2017' '3/17/2017' '3/24/2017' '3/28/2017'
 '4/3/2017' '4/4/2017' '4/20/2017' '4/24/2017' '4/25/2017' '5/8/2017'
 '5/20/2017' '6/1/2017' '6/12/2017' '7/2/2017' '7/4/2017' '7/5/2017'
 '7/17/2017' '8/16/2017' '8/22/2017' '8/25/2017' '8/31/2017' '9/5/2017'
 '9/6/2017' '9/14/2017' '9/22/2017' '9/27/2017' '10/9/2017' '10/10/2017'
 '10/15/2017' '10/26/2017' '11/2/2017' '11/7/2017' '11/11/2017'
 '11/14/2017' '12/5/2017' '12/7/2017' '12/8/2017' '12/12/2017'
 '12/19/2017' '12/23/2017' '1/14/2017' '1/21/2017' '2/16/2017' '2/18/2017'
 '3/8/2017' '4/27/2017' '5/12/2017' '6/19/2017' '6/26/2017' '7/3/2017'
 '8/3/2017' '8/13/2017' '8/19/2017' '8/23/2017' '8/28/2017' '8/30/2017'
 '9/13/2017' '9/28/2017' '10/19/2017' '12/6/2017' '12/27/2017' '1/13/2017'
 '2/4/2017' '2/5/2017' '2/11/2017' '3/14/2017' '3/25/2017' '3/26/2017'
 '4/12/2017' '4/14/2017' '4/13/2017' '5/11/2017' '6/21/2017' '7/1/2017'
 '7/23/2017' '7/27/2017' '8/29/2017' '9/24/2017' '9/29/2017' '10/29/2017'
 '11/16/2017' '12/16/2017' '1/6/2017' '1/31/2017' '2/1/2017' '2/2/2017'
 '2/6/2017' '2/10/2017' '2/12/2017' '2/22/2017' '3/18/2017' '3/21/2017'
 '3/22/2017' '3/31/2017' '4/9/2017' '4/22/2017' '4/23/2017' '5/2/2017'
 '5/5/2017' '5/19/2017' '6/9/2017' '6/16/2017' '6/15/2017' '7/6/2017'
 '7/7/2017' '7/12/2017' '7/29/2017' '9/1/2017' '9/11/2017' '9/8/2017'
 '9/18/2017' '9/20/2017' '10/11/2017' '10/12/2017' '11/1/2017' '11/8/2017'
 '11/24/2017' '1/1/2017' '2/14/2017' '5/10/2017' '5/15/2017' '9/23/2017'
 '10/25/2017' '2/17/2017' '1/10/2017' '12/25/2017' '5/24/2017' '1/7/2017'
 '5/7/2017' '7/9/2017' '10/5/2017' '11/10/2017' '11/18/2017' '1/12/2017'
 '4/2/2017' '4/18/2017' '5/4/2017' '5/30/2017' '5/31/2017' '6/4/2017'
 '8/10/2017' '9/15/2017' '10/28/2017' '10/30/2017' '11/19/2017'
 '11/26/2017' '12/13/2017' '12/17/2017' '2/27/2017' '4/1/2017' '6/20/2017'
 '6/24/2017' '8/6/2017' '9/4/2017' '9/25/2017' '12/15/2017' '3/23/2017'
 '5/29/2017' '6/8/2017' '3/9/2017' '6/11/2017' '6/30/2017' '3/3/2017'
 '3/5/2017' '3/15/2017' '6/13/2017' '8/5/2017' '12/3/2017' '12/18/2017'
 '6/17/2017' '7/30/2017' '9/21/2017' '11/6/2017' '1/3/2017' '1/9/2017'
 '1/28/2017' '3/2/2017' '4/11/2017' '5/18/2017' '5/23/2017' '5/3/2017'
 '6/3/2017' '6/22/2017' '7/8/2017' '7/15/2017' '7/21/2017' '7/26/2017'
 '10/7/2017' '10/17/2017' '11/12/2017' '12/4/2017' '12/22/2017'
 '12/28/2017' '1/11/2017' '3/7/2017' '4/7/2017' '4/21/2017' '6/25/2017'
 '8/11/2017' '8/14/2017' '11/20/2017' '12/9/2017' '8/8/2017' '11/13/2017'
 '11/28/2017' '2/28/2017' '11/5/2017' '12/21/2017' '12/26/2017'
 '10/3/2017' '12/30/2017' '3/1/2017' '8/15/2017' '10/22/2017' '11/27/2017'
 '1/19/2017' '3/6/2017']

Unique values in 'DAY': ['Sunday   ' 'Wednesday' 'Tuesday  ' 'Thursday ' 'Saturday ' 'Monday   '
 'Friday   ']

Unique values in 'ACCIDENT TYPE': ['FATAL' 'SIMPLE INJURY (HOSPITALISED)' 'GRIEVOUS INJURY'
 'VEHICLE DAMAGE ONLY (NON - I' 'SIMPLE INJURY (NON HOSPITALI']

Unique values in 'WEATHER CONDITION': ['FINE' 'MIST / FOG' 'HEAVY RAIN' 'CLOUDY' 'LIGHT RAIN'
 'FLOODING OF CAUSEWAYS / RIVULETS' 'VERY COLD' 'STRONG WIND' 'VERY HOT'
 'SMOKE / DUST' 'HAIL / SLEET']

Unique values in 'VEHICLE TYPE': ['UNKNOWN VEHICLE' 'BUS' 'MOTOR CYCLE' 'MOPED' 'CAR LMV' 'BICYCLE'
 'AUTORIKSHAW' 'LIGHT GOODS VEHIC' 'SCOOTER OR MOPED' 'TOURIST MAXI CAB|'
 'HEAVY GOODS VEHIC' 'TOURIST MOTOR CAB' 'MULTI AXLE GOODS' 'MINI BUS'
 'EARTH MOVING EQUI' 'DELIVERY VAN|டெலி' 'MAXI CAB|ம்யாக்ஸீ'
 'EDUCATIONAL INSTI' 'THREE WHEELER GOO' 'TRACTOR AGRICULTU'
 'MEDIUM GOODS VEHI' 'OMNI BUS LMV|ஓம்ந' 'ANIMAL DRAWN' 'LMV VAN'
 'AMBULANCE|ஆஂப்யுல' 'TRACTOR FOR COMME' 'MOTOR CYCLE IMPOR'
 'UTILITY VAN|யூடில' 'HEAVY GOODS VAN' 'TANKER|ட்யாஂகர்'
 'PRIVATE SERVICE V' 'LIGHT GOODS VAN' 'JEEP OR GYPSY LMV'
 'ROAD ROLLER|ரோட்' 'CRANE' 'CAMPER VAN|க்யாம்' 'POWER TILLER FOR'
 'ARTICULATED VEHIC' 'MOTOR CYCLE WITH' 'JEEP TAXI' 'TRAILER WITH PRIV'
 'MOBILE LAB VAN LM' 'MOBILE CLINIC|மொப' 'PASSENGER AND GOO'
 'CYCLE RICKSHAW' 'MOBILE LAB VAN HM' 'HAND DRAWN' 'HEERS CAR HMV|ஹீர'
 'LMV TRAILER' 'VEHICLE FITTED WI' 'CASH VAN|க்யாஶ் வ' 'TRACTOR WITH TRAI'
 'LMV IMPORTED' 'XRAY VAN|க்ஷ்ராய்' 'OMNI BUS MMV|ஓம்ந'
 'POSTAL VAN|போஸ்டல' 'BULLDOZER|புல்டோஸ' 'GOODS TRUCK CONTA'
 'THREE WHEELER PRI' 'SEMI DELUXE BUS|ச' 'TOW TRUCK|டோ ட்ரக' 'HMV TRAILER'
 'HULAGE VEHICLE|ஹு' 'TOURIST BUS|டூரிஸ' 'DELUXE BUS|டெலக்ஸ'
 'TRAILER FOR AGRIC' 'DOUBLE DECKER BUS' 'TRAILER FOR COMME' 'FORKLIFT'
 'TRACTOR FOR PVT U' 'MOBILE WORKSHOP|ம' 'MMV TRAILER' 'OMNI BUS HMV'
 'TREE TRIMMING VEH' 'RADIO TAXI|ரேடியோ' 'LMV COMPRESSOR|'
 'AIR CONDITIONED B' 'HEERS CAR LMV' 'ANIMAL AMBULANCE|' 'EXCAVATOR'
 'FIRE FIGHTER|பையர' 'MOBILE SERVICE VA' 'STATION WAGON|ஸ்ட'
 'SCOOTER WITH SIDE' 'MOBILE LIBRARY VA' 'INVALID CARRIAGE'
 'MOBILE CANTEEN|மொ' 'TOWER WEGON' 'SUV OR MUV' 'ROAD WATER SPRINK'
 'OMNI BUS PRIVATE' 'RECOVERY VEHICLE' 'POWER TILLER']

Unique values in 'COLLITION TYPE': ['HIT FROM REAR' 'HEAD ON' 'HIT PEDESTRIAN' 'HIT ANIMAL' 'SKIDDING'
 'HIT TREE' 'OTHERS' 'SIDE SWIPE' 'HIT FROM SIDE' 'HIT PARKED VEHICLE'
 'HIT OBJECT OFF ROAD' 'HIT OBJECT IN ROAD' 'OVERTURNING' 'RAN OFF ROAD'
 'OVERTURNING -NO COLLISION']

Unique values in 'ROAD TYPE': ['STATE HIGHWAY' 'OTHER DISTRICT RO' 'OTHER ROADS' 'VILLAGE ROADS'
 'NATIONAL HIGHWAY' 'MAJOR DISTRICT RO' 'NHAI' 'EXPRESS HIGHWAY']

Unique values in 'DRIVER NAME': ['Not applicable' 'Krishnamoorthy' 'MANIKANDAN' ... 'KARUVANRAYAN '
 'THANGARASU ' 'BALRAJ ']

Unique values in 'DRIVER AGE': [  0  50  30  45  35  40  60  22  28  38  37  55  42  65  46  53  58  67
  32  48  43  29  34  66  25  36  23  49  52  44  27  47  18  20  39  61
  54  26  33  24  57  16  21  19  41  12  68  17  59  31  56  51  63  81
  85  71  72  70  75  62  69 465  64  74  73  80  79  15  76   6  78  13
  83   3  82  14  10  77   7 424 377  84  87 333 305 540   9  88 278  11
 190  99 445   8  89  86   1 300 422 211 345   5 444 225 334]

Unique values in '24_HOUR_TIME': [datetime.time(20, 30) datetime.time(11, 30) datetime.time(11, 0)
 datetime.time(10, 30) datetime.time(16, 15) datetime.time(19, 30)
 datetime.time(11, 45) datetime.time(18, 15) datetime.time(5, 30)
 datetime.time(12, 20) datetime.time(15, 30) datetime.time(13, 0)
 datetime.time(9, 0) datetime.time(17, 30) datetime.time(19, 0)
 datetime.time(20, 0) datetime.time(17, 0) datetime.time(6, 30)
 datetime.time(10, 0) datetime.time(21, 0) datetime.time(18, 45)
 datetime.time(8, 30) datetime.time(16, 45) datetime.time(23, 50)
 datetime.time(12, 40) datetime.time(20, 20) datetime.time(8, 45)
 datetime.time(22, 0) datetime.time(10, 45) datetime.time(18, 30)
 datetime.time(15, 35) datetime.time(14, 0) datetime.time(16, 30)
 datetime.time(15, 45) datetime.time(12, 0) datetime.time(14, 40)
 datetime.time(18, 0) datetime.time(3, 0) datetime.time(7, 30)
 datetime.time(12, 30) datetime.time(14, 30) datetime.time(23, 0)
 datetime.time(21, 50) datetime.time(21, 45) datetime.time(11, 15)
 datetime.time(9, 15) datetime.time(15, 0) datetime.time(22, 45)
 datetime.time(19, 20) datetime.time(21, 30) datetime.time(19, 50)
 datetime.time(16, 0) datetime.time(18, 20) datetime.time(8, 15)
 datetime.time(12, 45) datetime.time(5, 0) datetime.time(17, 45)
 datetime.time(7, 50) datetime.time(0, 30) datetime.time(8, 0)
 datetime.time(9, 30) datetime.time(14, 45) datetime.time(17, 15)
 datetime.time(11, 40) datetime.time(16, 20) datetime.time(15, 10)
 datetime.time(20, 15) datetime.time(13, 15) datetime.time(6, 0)
 datetime.time(13, 30) datetime.time(1, 15) datetime.time(1, 30)
 datetime.time(5, 40) datetime.time(19, 10) datetime.time(19, 15)
 datetime.time(12, 15) datetime.time(9, 45) datetime.time(23, 45)
 datetime.time(1, 0) datetime.time(20, 10) datetime.time(22, 15)
 datetime.time(15, 15) datetime.time(4, 15) datetime.time(4, 30)
 datetime.time(2, 0) datetime.time(6, 10) datetime.time(23, 30)
 datetime.time(0, 5) datetime.time(18, 10) datetime.time(21, 15)
 datetime.time(14, 55) datetime.time(6, 20) datetime.time(0, 50)
 datetime.time(0, 15) datetime.time(14, 20) datetime.time(8, 5)
 datetime.time(21, 35) datetime.time(22, 30) datetime.time(7, 0)
 datetime.time(4, 0) datetime.time(14, 15) datetime.time(14, 10)
 datetime.time(17, 40) datetime.time(16, 50) datetime.time(10, 15)
 datetime.time(8, 10) datetime.time(16, 40) datetime.time(20, 45)
 datetime.time(6, 45) datetime.time(23, 40) datetime.time(6, 40)
 datetime.time(12, 35) datetime.time(3, 30) datetime.time(11, 10)
 datetime.time(19, 45) datetime.time(13, 50) datetime.time(15, 20)
 datetime.time(7, 45) datetime.time(20, 40) datetime.time(10, 25)
 datetime.time(0, 10) datetime.time(21, 10) datetime.time(6, 50)
 datetime.time(7, 15) datetime.time(11, 25) datetime.time(19, 40)
 datetime.time(12, 25) datetime.time(7, 20) datetime.time(15, 5)
 datetime.time(2, 45) datetime.time(4, 50) datetime.time(8, 20)
 datetime.time(13, 20) datetime.time(17, 50) datetime.time(19, 35)
 datetime.time(9, 20) datetime.time(22, 10) datetime.time(8, 40)
 datetime.time(23, 20) datetime.time(16, 25) datetime.time(5, 45)
 datetime.time(7, 55) datetime.time(7, 10) datetime.time(14, 5)
 datetime.time(2, 30) datetime.time(16, 10) datetime.time(13, 10)
 datetime.time(4, 45) datetime.time(5, 15) datetime.time(7, 25)
 datetime.time(10, 35) datetime.time(10, 55) datetime.time(11, 35)
 datetime.time(12, 55) datetime.time(9, 50) datetime.time(7, 40)
 datetime.time(18, 40) datetime.time(8, 55) datetime.time(12, 10)
 datetime.time(10, 20) datetime.time(9, 40) datetime.time(4, 20)
 datetime.time(11, 50) datetime.time(12, 5) datetime.time(15, 50)
 datetime.time(3, 40) datetime.time(18, 1) datetime.time(5, 50)
 datetime.time(13, 45) datetime.time(16, 44) datetime.time(0, 45)
 datetime.time(6, 15) datetime.time(22, 40) datetime.time(22, 50)
 datetime.time(3, 45) datetime.time(20, 55) datetime.time(1, 45)
 datetime.time(5, 35) datetime.time(8, 50) datetime.time(2, 15)
 datetime.time(22, 20) datetime.time(9, 10) datetime.time(21, 40)
 datetime.time(10, 10) datetime.time(1, 20) datetime.time(8, 25)
 datetime.time(18, 50) datetime.time(23, 15) datetime.time(12, 50)
 datetime.time(10, 50) datetime.time(15, 40) datetime.time(17, 35)
 datetime.time(0, 40) datetime.time(5, 10) datetime.time(13, 35)
 datetime.time(17, 20) datetime.time(23, 10) datetime.time(3, 50)
 datetime.time(2, 40) datetime.time(8, 35) datetime.time(22, 55)
 datetime.time(10, 40) datetime.time(6, 25) datetime.time(23, 25)
 datetime.time(5, 1) datetime.time(19, 25) datetime.time(22, 25)
 datetime.time(0, 35) datetime.time(13, 40) datetime.time(7, 5)
 datetime.time(10, 5) datetime.time(16, 35) datetime.time(11, 20)
 datetime.time(17, 25) datetime.time(1, 50) datetime.time(20, 50)
 datetime.time(16, 5) datetime.time(21, 25) datetime.time(21, 20)
 datetime.time(0, 20) datetime.time(17, 10) datetime.time(13, 12)
 datetime.time(14, 25) datetime.time(23, 55) datetime.time(15, 55)
 datetime.time(20, 5) datetime.time(3, 15) datetime.time(20, 25)
 datetime.time(14, 50) datetime.time(9, 25) datetime.time(0, 55)
 datetime.time(7, 35) datetime.time(5, 20) datetime.time(9, 59)
 datetime.time(9, 11) datetime.time(2, 20) datetime.time(3, 35)
 datetime.time(8, 18) datetime.time(12, 28) datetime.time(9, 55)
 datetime.time(21, 5) datetime.time(19, 55) datetime.time(18, 35)
 datetime.time(11, 17) datetime.time(9, 5) datetime.time(9, 52)
 datetime.time(2, 50) datetime.time(13, 5) datetime.time(2, 10)
 datetime.time(11, 55) datetime.time(6, 35) datetime.time(21, 55)
 datetime.time(11, 5) datetime.time(13, 55) datetime.time(14, 3)
 datetime.time(4, 40) datetime.time(17, 17) datetime.time(17, 55)
 datetime.time(3, 10) datetime.time(0, 25) datetime.time(9, 35)
 datetime.time(1, 10) datetime.time(12, 31) datetime.time(22, 35)
 datetime.time(1, 5) datetime.time(5, 5) datetime.time(7, 3)
 datetime.time(18, 2) datetime.time(18, 5) datetime.time(15, 25)
 datetime.time(7, 32) datetime.time(14, 35) datetime.time(23, 5)
 datetime.time(22, 5) datetime.time(11, 11) datetime.time(21, 51)
 datetime.time(2, 55) datetime.time(23, 35) datetime.time(21, 57)
 datetime.time(3, 20) datetime.time(0, 2) datetime.time(21, 6)
 datetime.time(4, 10) datetime.time(18, 25) datetime.time(19, 5)
 datetime.time(13, 25) datetime.time(23, 59) datetime.time(16, 55)
 datetime.time(16, 37) datetime.time(1, 2) datetime.time(2, 3)
 datetime.time(11, 3) datetime.time(10, 14) datetime.time(1, 40)
 datetime.time(10, 6) datetime.time(11, 18) datetime.time(5, 8)
 datetime.time(11, 13) datetime.time(9, 43) datetime.time(5, 25)
 datetime.time(6, 5) datetime.time(20, 35) datetime.time(4, 5)
 datetime.time(13, 9) datetime.time(4, 35) datetime.time(5, 4)
 datetime.time(12, 44) datetime.time(17, 58) datetime.time(2, 5)
 datetime.time(16, 4) datetime.time(14, 28) datetime.time(19, 22)
 datetime.time(6, 55) datetime.time(18, 55) datetime.time(3, 25)
 datetime.time(21, 22) datetime.time(4, 25) datetime.time(22, 6)
 datetime.time(1, 25) datetime.time(21, 53) datetime.time(19, 1)
 datetime.time(20, 17) datetime.time(14, 43) datetime.time(19, 16)
 datetime.time(2, 25) datetime.time(14, 12) datetime.time(13, 52)
 datetime.time(23, 43) datetime.time(5, 55) datetime.time(21, 27)
 datetime.time(20, 16) datetime.time(0, 1) datetime.time(1, 55)
 datetime.time(14, 33) datetime.time(10, 36) datetime.time(18, 23)
 datetime.time(19, 38) datetime.time(17, 5) datetime.time(16, 12)
 datetime.time(3, 5) datetime.time(2, 35) datetime.time(12, 53)
 datetime.time(17, 12) datetime.time(9, 26) datetime.time(20, 56)
 datetime.time(19, 8) datetime.time(22, 3) datetime.time(20, 14)
 datetime.time(22, 1) datetime.time(10, 12) datetime.time(2, 4)
 datetime.time(7, 46) datetime.time(20, 37) datetime.time(15, 54)
 datetime.time(23, 36) datetime.time(17, 41) datetime.time(7, 12)
 datetime.time(22, 22) datetime.time(16, 16) datetime.time(4, 55)
 datetime.time(3, 16) datetime.time(8, 59) datetime.time(1, 35)
 datetime.time(18, 11) datetime.time(21, 33) datetime.time(10, 46)
 datetime.time(19, 28)]

Unique values in '24_HOUR_TIME_STR': ['20:30' '11:30' '11:00' '10:30' '16:15' '19:30' '11:45' '18:15' '05:30'
 '12:20' '15:30' '13:00' '09:00' '17:30' '19:00' '20:00' '17:00' '06:30'
 '10:00' '21:00' '18:45' '08:30' '16:45' '23:50' '12:40' '20:20' '08:45'
 '22:00' '10:45' '18:30' '15:35' '14:00' '16:30' '15:45' '12:00' '14:40'
 '18:00' '03:00' '07:30' '12:30' '14:30' '23:00' '21:50' '21:45' '11:15'
 '09:15' '15:00' '22:45' '19:20' '21:30' '19:50' '16:00' '18:20' '08:15'
 '12:45' '05:00' '17:45' '07:50' '00:30' '08:00' '09:30' '14:45' '17:15'
 '11:40' '16:20' '15:10' '20:15' '13:15' '06:00' '13:30' '01:15' '01:30'
 '05:40' '19:10' '19:15' '12:15' '09:45' '23:45' '01:00' '20:10' '22:15'
 '15:15' '04:15' '04:30' '02:00' '06:10' '23:30' '00:05' '18:10' '21:15'
 '14:55' '06:20' '00:50' '00:15' '14:20' '08:05' '21:35' '22:30' '07:00'
 '04:00' '14:15' '14:10' '17:40' '16:50' '10:15' '08:10' '16:40' '20:45'
 '06:45' '23:40' '06:40' '12:35' '03:30' '11:10' '19:45' '13:50' '15:20'
 '07:45' '20:40' '10:25' '00:10' '21:10' '06:50' '07:15' '11:25' '19:40'
 '12:25' '07:20' '15:05' '02:45' '04:50' '08:20' '13:20' '17:50' '19:35'
 '09:20' '22:10' '08:40' '23:20' '16:25' '05:45' '07:55' '07:10' '14:05'
 '02:30' '16:10' '13:10' '04:45' '05:15' '07:25' '10:35' '10:55' '11:35'
 '12:55' '09:50' '07:40' '18:40' '08:55' '12:10' '10:20' '09:40' '04:20'
 '11:50' '12:05' '15:50' '03:40' '18:01' '05:50' '13:45' '16:44' '00:45'
 '06:15' '22:40' '22:50' '03:45' '20:55' '01:45' '05:35' '08:50' '02:15'
 '22:20' '09:10' '21:40' '10:10' '01:20' '08:25' '18:50' '23:15' '12:50'
 '10:50' '15:40' '17:35' '00:40' '05:10' '13:35' '17:20' '23:10' '03:50'
 '02:40' '08:35' '22:55' '10:40' '06:25' '23:25' '05:01' '19:25' '22:25'
 '00:35' '13:40' '07:05' '10:05' '16:35' '11:20' '17:25' '01:50' '20:50'
 '16:05' '21:25' '21:20' '00:20' '17:10' '13:12' '14:25' '23:55' '15:55'
 '20:05' '03:15' '20:25' '14:50' '09:25' '00:55' '07:35' '05:20' '09:59'
 '09:11' '02:20' '03:35' '08:18' '12:28' '09:55' '21:05' '19:55' '18:35'
 '11:17' '09:05' '09:52' '02:50' '13:05' '02:10' '11:55' '06:35' '21:55'
 '11:05' '13:55' '14:03' '04:40' '17:17' '17:55' '03:10' '00:25' '09:35'
 '01:10' '12:31' '22:35' '01:05' '05:05' '07:03' '18:02' '18:05' '15:25'
 '07:32' '14:35' '23:05' '22:05' '11:11' '21:51' '02:55' '23:35' '21:57'
 '03:20' '00:02' '21:06' '04:10' '18:25' '19:05' '13:25' '23:59' '16:55'
 '16:37' '01:02' '02:03' '11:03' '10:14' '01:40' '10:06' '11:18' '05:08'
 '11:13' '09:43' '05:25' '06:05' '20:35' '04:05' '13:09' '04:35' '05:04'
 '12:44' '17:58' '02:05' '16:04' '14:28' '19:22' '06:55' '18:55' '03:25'
 '21:22' '04:25' '22:06' '01:25' '21:53' '19:01' '20:17' '14:43' '19:16'
 '02:25' '14:12' '13:52' '23:43' '05:55' '21:27' '20:16' '00:01' '01:55'
 '14:33' '10:36' '18:23' '19:38' '17:05' '16:12' '03:05' '02:35' '12:53'
 '17:12' '09:26' '20:56' '19:08' '22:03' '20:14' '22:01' '10:12' '02:04'
 '07:46' '20:37' '15:54' '23:36' '17:41' '07:12' '22:22' '16:16' '04:55'
 '03:16' '08:59' '01:35' '18:11' '21:33' '10:46' '19:28']

I see a lot of issues and problems here, we will be addressing them one by one

# First issue : Spaces from String Columns:

In [16]:
import pandas as pd
import numpy as np

# Step 1: Trim spaces from all string columns
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

/tmp/ipykernel_74521/2516192401.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

# Second issue : Similar Cities with different names

In [17]:

# Dictionary mapping current district entries to the standardized names
replacements = {
    'COIMBATORE CITY': 'COIMBATORE',  # Unifying Coimbatore entries
    'MADURAI CITY': 'MADURAI',        # Unifying Madurai entries
    'SALEM CITY': 'SALEM',            # Unifying Salem entries
    'TIRUNELVELI CITY': 'TIRUNELVELI',# Unifying Tirunelveli entries
    'TRICHY CITY': 'TRICHY',          # Unifying Trichy entries
    'TIRUPPUR CITY': 'TIRUPPUR'       # Unifying Tiruppur entries
}

# Step 2: Replace the 'DISTRICT' column values based on the replacements dictionary
df['DISTRICT'] = df['DISTRICT'].replace(replacements)

print("Unique values in 'DISTRICT' after replacement:", df['DISTRICT'].unique())

Unique values in 'DISTRICT' after replacement: ['ARIYALUR' 'COIMBATORE' 'CHENNAI CITY' 'CHENNAI' 'CUDDALORE' 'DINDIGUL'
 'DHARMAPURI' 'ERODE' 'KANYAKUMARI' 'KANCHEEPURAM' 'KRISHNAGIRI' 'KARUR'
 'MADURAI' 'NAGAPATTINAM' 'NILGIRIS' 'NAMAKKAL' 'PERAMBALUR' 'PUDUKKOTTAI'
 'RAMANATHAPURAM' 'SALEM' 'SIVAGANGAI' 'THANJAVUR' 'TIRUNELVELI' 'THENI'
 'TIRUPPUR' 'TRICHY' 'TUTICORIN' 'THIRUVALLUR' 'THIRUVANNAMALAI'
 'TIRUVARUR' 'VELLORE' 'VIRUDHUNAGAR' 'VILLUPURAM']

# Third issue : Unrealistic ages of drivers

In [18]:
# Define unrealistic age thresholds
age_min_threshold = 16  # Minimum realistic age for drivers
age_max_threshold = 100  # Maximum realistic age for drivers

# Count the number of records with unrealistic age values
unrealistic_ages_count = df[(df['DRIVER AGE'] < age_min_threshold) | (df['DRIVER AGE'] > age_max_threshold)].shape[0]

print(f"Number of records with unrealistic driver age values: {unrealistic_ages_count}")

Number of records with unrealistic driver age values: 3593

In [19]:
def correct_age(age):
    # Define the realistic age range
    min_age = 16
    max_age = 100
    
    # Convert age to string to easily work with individual characters
    age_str = str(age)
    
    # Check if the age is already within the realistic range
    if min_age <= age <= max_age:
        return age
    
    # Check if the first two digits form a realistic age
    if len(age_str) >= 2 and min_age <= int(age_str[:2]) <= max_age:
        return int(age_str[:2])
    
    # Check if the last two digits form a realistic age
    if len(age_str) >= 2 and min_age <= int(age_str[-2:]) <= max_age:
        return int(age_str[-2:])
    
    # Return the original age if no conditions are met
    return age

# Apply the correct_age function to the 'DRIVER AGE' column
df['DRIVER AGE'] = df['DRIVER AGE'].apply(correct_age)

# The records that still didn't get fixed after the function are to be removed
df = df[(df['DRIVER AGE'] >= 16) & (df['DRIVER AGE'] <= 100)]

# Fourth issue : Issues with the format of Date

In [20]:
# Convert 'DATE' column to datetime, specifying the format to match your description
# Even though pandas is generally good at inferring formats, specifying it helps avoid ambiguity
df['DATE'] = pd.to_datetime(df['DATE'], format='%m/%d/%Y', errors='coerce')

# This explicitly tells pandas that the format is month/day/year,
# and it should be able to handle single-digit months without leading zeros correctly.

# Check for any conversion errors resulting in NaT values
nat_count = df['DATE'].isna().sum()
if nat_count > 0:
    print(f"There were {nat_count} rows where 'DATE' could not be converted and resulted in NaT.")

Let's check out if there are any other issues that jump out at us

In [21]:
# Find and print unique values for each column
for column in df.columns:
    unique_values = df[column].unique()
    print(f"Unique values in '{column}': {unique_values}\n")

Unique values in 'DISTRICT': ['ARIYALUR' 'COIMBATORE' 'CHENNAI CITY' 'CHENNAI' 'CUDDALORE' 'DINDIGUL'
 'DHARMAPURI' 'ERODE' 'KANYAKUMARI' 'KANCHEEPURAM' 'KRISHNAGIRI' 'KARUR'
 'MADURAI' 'NAGAPATTINAM' 'NILGIRIS' 'NAMAKKAL' 'PERAMBALUR' 'PUDUKKOTTAI'
 'RAMANATHAPURAM' 'SALEM' 'SIVAGANGAI' 'THANJAVUR' 'TIRUNELVELI' 'THENI'
 'TIRUPPUR' 'TRICHY' 'TUTICORIN' 'THIRUVALLUR' 'THIRUVANNAMALAI'
 'TIRUVARUR' 'VELLORE' 'VIRUDHUNAGAR' 'VILLUPURAM']

Unique values in 'POLICE STATION': ['ANDIMADAM' 'ARIYALUR' 'IRUMBULIKURICHI' ... 'Uthukuzhi' 'Vellakoil'
 'amaravathy']

Unique values in 'DATE': <DatetimeArray>
['2017-01-18 00:00:00', '2017-01-24 00:00:00', '2017-01-15 00:00:00',
 '2017-01-26 00:00:00', '2017-02-07 00:00:00', '2017-02-09 00:00:00',
 '2017-02-19 00:00:00', '2017-02-23 00:00:00', '2017-03-04 00:00:00',
 '2017-03-11 00:00:00',
 ...
 '2017-12-26 00:00:00', '2017-10-03 00:00:00', '2017-12-30 00:00:00',
 '2017-03-01 00:00:00', '2017-11-13 00:00:00', '2017-08-15 00:00:00',
 '2017-10-22 00:00:00', '2017-11-27 00:00:00', '2017-01-19 00:00:00',
 '2017-03-06 00:00:00']
Length: 365, dtype: datetime64[ns]

Unique values in 'DAY': ['Wednesday' 'Tuesday' 'Sunday' 'Thursday' 'Saturday' 'Monday' 'Friday']

Unique values in 'ACCIDENT TYPE': ['FATAL' 'SIMPLE INJURY (HOSPITALISED)' 'GRIEVOUS INJURY'
 'VEHICLE DAMAGE ONLY (NON - I' 'SIMPLE INJURY (NON HOSPITALI']

Unique values in 'WEATHER CONDITION': ['FINE' 'MIST / FOG' 'HEAVY RAIN' 'CLOUDY' 'LIGHT RAIN'
 'FLOODING OF CAUSEWAYS / RIVULETS' 'VERY COLD' 'STRONG WIND' 'VERY HOT'
 'SMOKE / DUST' 'HAIL / SLEET']

Unique values in 'VEHICLE TYPE': ['BUS' 'MOTOR CYCLE' 'MOPED' 'CAR LMV' 'BICYCLE' 'AUTORIKSHAW'
 'LIGHT GOODS VEHIC' 'UNKNOWN VEHICLE' 'SCOOTER OR MOPED'
 'TOURIST MAXI CAB|' 'HEAVY GOODS VEHIC' 'TOURIST MOTOR CAB'
 'MULTI AXLE GOODS' 'MINI BUS' 'EARTH MOVING EQUI' 'DELIVERY VAN|டெலி'
 'MAXI CAB|ம்யாக்ஸீ' 'EDUCATIONAL INSTI' 'THREE WHEELER GOO'
 'TRACTOR AGRICULTU' 'MEDIUM GOODS VEHI' 'OMNI BUS LMV|ஓம்ந'
 'ANIMAL DRAWN' 'LMV VAN' 'AMBULANCE|ஆஂப்யுல' 'TRACTOR FOR COMME'
 'MOTOR CYCLE IMPOR' 'UTILITY VAN|யூடில' 'HEAVY GOODS VAN'
 'TANKER|ட்யாஂகர்' 'PRIVATE SERVICE V' 'LIGHT GOODS VAN'
 'JEEP OR GYPSY LMV' 'ROAD ROLLER|ரோட்' 'CRANE' 'CAMPER VAN|க்யாம்'
 'POWER TILLER FOR' 'ARTICULATED VEHIC' 'MOTOR CYCLE WITH' 'JEEP TAXI'
 'TRAILER WITH PRIV' 'MOBILE LAB VAN LM' 'MOBILE CLINIC|மொப'
 'PASSENGER AND GOO' 'CYCLE RICKSHAW' 'MOBILE LAB VAN HM' 'HAND DRAWN'
 'HEERS CAR HMV|ஹீர' 'LMV TRAILER' 'VEHICLE FITTED WI' 'CASH VAN|க்யாஶ் வ'
 'TRACTOR WITH TRAI' 'LMV IMPORTED' 'XRAY VAN|க்ஷ்ராய்'
 'OMNI BUS MMV|ஓம்ந' 'POSTAL VAN|போஸ்டல' 'BULLDOZER|புல்டோஸ'
 'GOODS TRUCK CONTA' 'THREE WHEELER PRI' 'SEMI DELUXE BUS|ச'
 'TOW TRUCK|டோ ட்ரக' 'HULAGE VEHICLE|ஹு' 'TOURIST BUS|டூரிஸ'
 'DELUXE BUS|டெலக்ஸ' 'TRAILER FOR AGRIC' 'DOUBLE DECKER BUS'
 'TRAILER FOR COMME' 'FORKLIFT' 'TRACTOR FOR PVT U' 'MOBILE WORKSHOP|ம'
 'MMV TRAILER' 'HMV TRAILER' 'OMNI BUS HMV' 'TREE TRIMMING VEH'
 'RADIO TAXI|ரேடியோ' 'LMV COMPRESSOR|' 'AIR CONDITIONED B' 'HEERS CAR LMV'
 'ANIMAL AMBULANCE|' 'EXCAVATOR' 'FIRE FIGHTER|பையர' 'MOBILE SERVICE VA'
 'STATION WAGON|ஸ்ட' 'SCOOTER WITH SIDE' 'MOBILE LIBRARY VA'
 'INVALID CARRIAGE' 'MOBILE CANTEEN|மொ' 'SUV OR MUV' 'ROAD WATER SPRINK'
 'OMNI BUS PRIVATE' 'RECOVERY VEHICLE' 'POWER TILLER' 'TOWER WEGON']

Unique values in 'COLLITION TYPE': ['HEAD ON' 'HIT PEDESTRIAN' 'HIT FROM REAR' 'HIT ANIMAL' 'SKIDDING'
 'HIT TREE' 'OTHERS' 'SIDE SWIPE' 'HIT FROM SIDE' 'HIT PARKED VEHICLE'
 'HIT OBJECT OFF ROAD' 'HIT OBJECT IN ROAD' 'OVERTURNING' 'RAN OFF ROAD'
 'OVERTURNING -NO COLLISION']

Unique values in 'ROAD TYPE': ['STATE HIGHWAY' 'OTHER DISTRICT RO' 'OTHER ROADS' 'VILLAGE ROADS'
 'NATIONAL HIGHWAY' 'MAJOR DISTRICT RO' 'NHAI' 'EXPRESS HIGHWAY']

Unique values in 'DRIVER NAME': ['Krishnamoorthy' 'MANIKANDAN' 'VENGATAPATHI RAJ' ... 'KARTHEKEYAN'
 'KOWSIKKUMAR' 'KARUVANRAYAN']

Unique values in 'DRIVER AGE': [50 30 45 35 40 60 22 28 38 37 55 42 65 46 53 58 67 32 48 43 29 34 66 25
 36 23 49 52 44 27 47 18 20 39 61 54 26 33 24 57 16 21 19 41 68 17 59 31
 56 51 63 81 85 71 72 70 75 62 69 64 74 73 80 79 76 78 83 82 77 84 87 88
 99 89 86]

Unique values in '24_HOUR_TIME': [datetime.time(11, 30) datetime.time(11, 0) datetime.time(10, 30)
 datetime.time(16, 15) datetime.time(19, 30) datetime.time(11, 45)
 datetime.time(18, 15) datetime.time(5, 30) datetime.time(12, 20)
 datetime.time(15, 30) datetime.time(13, 0) datetime.time(9, 0)
 datetime.time(17, 30) datetime.time(19, 0) datetime.time(20, 0)
 datetime.time(20, 30) datetime.time(17, 0) datetime.time(6, 30)
 datetime.time(10, 0) datetime.time(21, 0) datetime.time(18, 45)
 datetime.time(8, 30) datetime.time(16, 45) datetime.time(12, 40)
 datetime.time(8, 45) datetime.time(22, 0) datetime.time(10, 45)
 datetime.time(18, 30) datetime.time(15, 35) datetime.time(14, 0)
 datetime.time(16, 30) datetime.time(15, 45) datetime.time(12, 0)
 datetime.time(14, 40) datetime.time(18, 0) datetime.time(3, 0)
 datetime.time(7, 30) datetime.time(12, 30) datetime.time(14, 30)
 datetime.time(23, 0) datetime.time(21, 50) datetime.time(21, 45)
 datetime.time(11, 15) datetime.time(9, 15) datetime.time(15, 0)
 datetime.time(22, 45) datetime.time(19, 20) datetime.time(16, 0)
 datetime.time(18, 20) datetime.time(8, 15) datetime.time(12, 45)
 datetime.time(5, 0) datetime.time(17, 45) datetime.time(7, 50)
 datetime.time(0, 30) datetime.time(8, 0) datetime.time(9, 30)
 datetime.time(14, 45) datetime.time(17, 15) datetime.time(11, 40)
 datetime.time(21, 30) datetime.time(16, 20) datetime.time(15, 10)
 datetime.time(20, 15) datetime.time(13, 15) datetime.time(6, 0)
 datetime.time(13, 30) datetime.time(1, 15) datetime.time(1, 30)
 datetime.time(5, 40) datetime.time(19, 10) datetime.time(19, 15)
 datetime.time(12, 15) datetime.time(9, 45) datetime.time(23, 45)
 datetime.time(1, 0) datetime.time(20, 10) datetime.time(22, 15)
 datetime.time(15, 15) datetime.time(4, 15) datetime.time(4, 30)
 datetime.time(6, 10) datetime.time(23, 30) datetime.time(0, 5)
 datetime.time(21, 15) datetime.time(14, 55) datetime.time(6, 20)
 datetime.time(0, 50) datetime.time(8, 5) datetime.time(21, 35)
 datetime.time(22, 30) datetime.time(0, 15) datetime.time(7, 0)
 datetime.time(4, 0) datetime.time(14, 15) datetime.time(14, 10)
 datetime.time(17, 40) datetime.time(16, 50) datetime.time(10, 15)
 datetime.time(8, 10) datetime.time(16, 40) datetime.time(20, 45)
 datetime.time(6, 45) datetime.time(23, 40) datetime.time(6, 40)
 datetime.time(12, 35) datetime.time(3, 30) datetime.time(19, 45)
 datetime.time(13, 50) datetime.time(7, 45) datetime.time(20, 40)
 datetime.time(19, 50) datetime.time(10, 25) datetime.time(0, 10)
 datetime.time(21, 10) datetime.time(6, 50) datetime.time(7, 15)
 datetime.time(11, 25) datetime.time(19, 40) datetime.time(12, 25)
 datetime.time(7, 20) datetime.time(15, 5) datetime.time(2, 45)
 datetime.time(2, 0) datetime.time(4, 50) datetime.time(8, 20)
 datetime.time(13, 20) datetime.time(14, 20) datetime.time(17, 50)
 datetime.time(19, 35) datetime.time(9, 20) datetime.time(22, 10)
 datetime.time(8, 40) datetime.time(23, 20) datetime.time(16, 25)
 datetime.time(5, 45) datetime.time(20, 20) datetime.time(7, 55)
 datetime.time(7, 10) datetime.time(14, 5) datetime.time(2, 30)
 datetime.time(16, 10) datetime.time(13, 10) datetime.time(4, 45)
 datetime.time(5, 15) datetime.time(7, 25) datetime.time(10, 35)
 datetime.time(10, 55) datetime.time(12, 55) datetime.time(9, 50)
 datetime.time(7, 40) datetime.time(15, 20) datetime.time(18, 40)
 datetime.time(8, 55) datetime.time(12, 10) datetime.time(10, 20)
 datetime.time(9, 40) datetime.time(4, 20) datetime.time(11, 10)
 datetime.time(11, 50) datetime.time(12, 5) datetime.time(15, 50)
 datetime.time(3, 40) datetime.time(18, 1) datetime.time(5, 50)
 datetime.time(13, 45) datetime.time(16, 44) datetime.time(0, 45)
 datetime.time(6, 15) datetime.time(22, 40) datetime.time(22, 50)
 datetime.time(3, 45) datetime.time(20, 55) datetime.time(1, 45)
 datetime.time(5, 35) datetime.time(8, 50) datetime.time(2, 15)
 datetime.time(22, 20) datetime.time(9, 10) datetime.time(21, 40)
 datetime.time(10, 10) datetime.time(1, 20) datetime.time(8, 25)
 datetime.time(23, 50) datetime.time(18, 50) datetime.time(23, 15)
 datetime.time(12, 50) datetime.time(10, 50) datetime.time(15, 40)
 datetime.time(17, 35) datetime.time(0, 40) datetime.time(5, 10)
 datetime.time(13, 35) datetime.time(17, 20) datetime.time(23, 10)
 datetime.time(3, 50) datetime.time(2, 40) datetime.time(8, 35)
 datetime.time(22, 55) datetime.time(10, 40) datetime.time(6, 25)
 datetime.time(23, 25) datetime.time(5, 1) datetime.time(19, 25)
 datetime.time(22, 25) datetime.time(0, 35) datetime.time(13, 40)
 datetime.time(7, 5) datetime.time(10, 5) datetime.time(16, 35)
 datetime.time(11, 20) datetime.time(17, 25) datetime.time(1, 50)
 datetime.time(20, 50) datetime.time(16, 5) datetime.time(21, 25)
 datetime.time(21, 20) datetime.time(0, 20) datetime.time(17, 10)
 datetime.time(14, 25) datetime.time(23, 55) datetime.time(15, 55)
 datetime.time(11, 35) datetime.time(3, 15) datetime.time(20, 25)
 datetime.time(14, 50) datetime.time(0, 55) datetime.time(7, 35)
 datetime.time(5, 20) datetime.time(9, 59) datetime.time(9, 11)
 datetime.time(2, 20) datetime.time(3, 35) datetime.time(8, 18)
 datetime.time(18, 10) datetime.time(12, 28) datetime.time(9, 55)
 datetime.time(21, 5) datetime.time(19, 55) datetime.time(18, 35)
 datetime.time(11, 17) datetime.time(9, 5) datetime.time(9, 52)
 datetime.time(13, 5) datetime.time(2, 10) datetime.time(11, 55)
 datetime.time(6, 35) datetime.time(21, 55) datetime.time(11, 5)
 datetime.time(13, 55) datetime.time(14, 3) datetime.time(4, 40)
 datetime.time(17, 17) datetime.time(17, 55) datetime.time(3, 10)
 datetime.time(0, 25) datetime.time(9, 35) datetime.time(1, 10)
 datetime.time(12, 31) datetime.time(22, 35) datetime.time(1, 5)
 datetime.time(5, 5) datetime.time(7, 3) datetime.time(18, 2)
 datetime.time(20, 5) datetime.time(18, 5) datetime.time(15, 25)
 datetime.time(7, 32) datetime.time(14, 35) datetime.time(23, 5)
 datetime.time(22, 5) datetime.time(11, 11) datetime.time(21, 51)
 datetime.time(2, 55) datetime.time(23, 35) datetime.time(21, 57)
 datetime.time(2, 50) datetime.time(3, 20) datetime.time(0, 2)
 datetime.time(21, 6) datetime.time(4, 10) datetime.time(18, 25)
 datetime.time(19, 5) datetime.time(13, 25) datetime.time(23, 59)
 datetime.time(16, 55) datetime.time(16, 37) datetime.time(1, 2)
 datetime.time(2, 3) datetime.time(11, 3) datetime.time(10, 14)
 datetime.time(1, 40) datetime.time(10, 6) datetime.time(11, 18)
 datetime.time(5, 8) datetime.time(11, 13) datetime.time(5, 25)
 datetime.time(6, 5) datetime.time(20, 35) datetime.time(9, 25)
 datetime.time(4, 5) datetime.time(13, 9) datetime.time(4, 35)
 datetime.time(5, 4) datetime.time(12, 44) datetime.time(17, 58)
 datetime.time(2, 5) datetime.time(16, 4) datetime.time(14, 28)
 datetime.time(19, 22) datetime.time(6, 55) datetime.time(18, 55)
 datetime.time(3, 25) datetime.time(21, 22) datetime.time(4, 25)
 datetime.time(1, 25) datetime.time(21, 53) datetime.time(19, 1)
 datetime.time(20, 17) datetime.time(14, 43) datetime.time(19, 16)
 datetime.time(2, 25) datetime.time(14, 12) datetime.time(13, 52)
 datetime.time(5, 55) datetime.time(21, 27) datetime.time(20, 16)
 datetime.time(0, 1) datetime.time(1, 55) datetime.time(14, 33)
 datetime.time(10, 36) datetime.time(18, 23) datetime.time(19, 38)
 datetime.time(17, 5) datetime.time(16, 12) datetime.time(3, 5)
 datetime.time(12, 53) datetime.time(17, 12) datetime.time(9, 26)
 datetime.time(20, 56) datetime.time(19, 8) datetime.time(22, 3)
 datetime.time(20, 14) datetime.time(22, 1) datetime.time(10, 12)
 datetime.time(2, 4) datetime.time(7, 46) datetime.time(20, 37)
 datetime.time(15, 54) datetime.time(23, 36) datetime.time(17, 41)
 datetime.time(7, 12) datetime.time(22, 22) datetime.time(16, 16)
 datetime.time(4, 55) datetime.time(3, 16) datetime.time(8, 59)
 datetime.time(1, 35) datetime.time(21, 33) datetime.time(10, 46)
 datetime.time(19, 28)]

Unique values in '24_HOUR_TIME_STR': ['11:30' '11:00' '10:30' '16:15' '19:30' '11:45' '18:15' '05:30' '12:20'
 '15:30' '13:00' '09:00' '17:30' '19:00' '20:00' '20:30' '17:00' '06:30'
 '10:00' '21:00' '18:45' '08:30' '16:45' '12:40' '08:45' '22:00' '10:45'
 '18:30' '15:35' '14:00' '16:30' '15:45' '12:00' '14:40' '18:00' '03:00'
 '07:30' '12:30' '14:30' '23:00' '21:50' '21:45' '11:15' '09:15' '15:00'
 '22:45' '19:20' '16:00' '18:20' '08:15' '12:45' '05:00' '17:45' '07:50'
 '00:30' '08:00' '09:30' '14:45' '17:15' '11:40' '21:30' '16:20' '15:10'
 '20:15' '13:15' '06:00' '13:30' '01:15' '01:30' '05:40' '19:10' '19:15'
 '12:15' '09:45' '23:45' '01:00' '20:10' '22:15' '15:15' '04:15' '04:30'
 '06:10' '23:30' '00:05' '21:15' '14:55' '06:20' '00:50' '08:05' '21:35'
 '22:30' '00:15' '07:00' '04:00' '14:15' '14:10' '17:40' '16:50' '10:15'
 '08:10' '16:40' '20:45' '06:45' '23:40' '06:40' '12:35' '03:30' '19:45'
 '13:50' '07:45' '20:40' '19:50' '10:25' '00:10' '21:10' '06:50' '07:15'
 '11:25' '19:40' '12:25' '07:20' '15:05' '02:45' '02:00' '04:50' '08:20'
 '13:20' '14:20' '17:50' '19:35' '09:20' '22:10' '08:40' '23:20' '16:25'
 '05:45' '20:20' '07:55' '07:10' '14:05' '02:30' '16:10' '13:10' '04:45'
 '05:15' '07:25' '10:35' '10:55' '12:55' '09:50' '07:40' '15:20' '18:40'
 '08:55' '12:10' '10:20' '09:40' '04:20' '11:10' '11:50' '12:05' '15:50'
 '03:40' '18:01' '05:50' '13:45' '16:44' '00:45' '06:15' '22:40' '22:50'
 '03:45' '20:55' '01:45' '05:35' '08:50' '02:15' '22:20' '09:10' '21:40'
 '10:10' '01:20' '08:25' '23:50' '18:50' '23:15' '12:50' '10:50' '15:40'
 '17:35' '00:40' '05:10' '13:35' '17:20' '23:10' '03:50' '02:40' '08:35'
 '22:55' '10:40' '06:25' '23:25' '05:01' '19:25' '22:25' '00:35' '13:40'
 '07:05' '10:05' '16:35' '11:20' '17:25' '01:50' '20:50' '16:05' '21:25'
 '21:20' '00:20' '17:10' '14:25' '23:55' '15:55' '11:35' '03:15' '20:25'
 '14:50' '00:55' '07:35' '05:20' '09:59' '09:11' '02:20' '03:35' '08:18'
 '18:10' '12:28' '09:55' '21:05' '19:55' '18:35' '11:17' '09:05' '09:52'
 '13:05' '02:10' '11:55' '06:35' '21:55' '11:05' '13:55' '14:03' '04:40'
 '17:17' '17:55' '03:10' '00:25' '09:35' '01:10' '12:31' '22:35' '01:05'
 '05:05' '07:03' '18:02' '20:05' '18:05' '15:25' '07:32' '14:35' '23:05'
 '22:05' '11:11' '21:51' '02:55' '23:35' '21:57' '02:50' '03:20' '00:02'
 '21:06' '04:10' '18:25' '19:05' '13:25' '23:59' '16:55' '16:37' '01:02'
 '02:03' '11:03' '10:14' '01:40' '10:06' '11:18' '05:08' '11:13' '05:25'
 '06:05' '20:35' '09:25' '04:05' '13:09' '04:35' '05:04' '12:44' '17:58'
 '02:05' '16:04' '14:28' '19:22' '06:55' '18:55' '03:25' '21:22' '04:25'
 '01:25' '21:53' '19:01' '20:17' '14:43' '19:16' '02:25' '14:12' '13:52'
 '05:55' '21:27' '20:16' '00:01' '01:55' '14:33' '10:36' '18:23' '19:38'
 '17:05' '16:12' '03:05' '12:53' '17:12' '09:26' '20:56' '19:08' '22:03'
 '20:14' '22:01' '10:12' '02:04' '07:46' '20:37' '15:54' '23:36' '17:41'
 '07:12' '22:22' '16:16' '04:55' '03:16' '08:59' '01:35' '21:33' '10:46'
 '19:28']

In [22]:
df.head()

,DISTRICT,POLICE STATION,DATE,DAY,ACCIDENT TYPE,WEATHER CONDITION,VEHICLE TYPE,COLLITION TYPE,ROAD TYPE,DRIVER NAME,DRIVER AGE,24_HOUR_TIME,24_HOUR_TIME_STR
1,ARIYALUR,ANDIMADAM,2017-01-18,Wednesday,FATAL,FINE,BUS,HEAD ON,STATE HIGHWAY,Krishnamoorthy,50,11:30:00,11:30
2,ARIYALUR,ANDIMADAM,2017-01-24,Tuesday,SIMPLE INJURY (HOSPITALISED),FINE,MOTOR CYCLE,HIT PEDESTRIAN,STATE HIGHWAY,MANIKANDAN,30,11:00:00,11:00
3,ARIYALUR,ANDIMADAM,2017-01-15,Sunday,FATAL,FINE,MOPED,HIT FROM REAR,STATE HIGHWAY,VENGATAPATHI RAJ,30,10:30:00,10:30
4,ARIYALUR,ANDIMADAM,2017-01-26,Thursday,SIMPLE INJURY (HOSPITALISED),FINE,CAR LMV,HIT FROM REAR,STATE HIGHWAY,Sivasankaran,45,16:15:00,16:15
5,ARIYALUR,ANDIMADAM,2017-02-07,Tuesday,FATAL,FINE,MOTOR CYCLE,HIT PEDESTRIAN,STATE HIGHWAY,Mariya Alexonder,35,19:30:00,19:30

Driver Name isn't important as well, but before we drop it, I want to check if there's any driver who's had multiple accidents. If there is, then we might want to keep it

In [23]:
# Count the occurrences of each driver's name
driver_accidents_count = df['DRIVER NAME'].value_counts()

# Filter out drivers with more than one accident
multiple_accidents_drivers = driver_accidents_count[driver_accidents_count > 1]

# Display drivers who had multiple accidents
print(multiple_accidents_drivers)

# Check if there are any drivers with multiple accidents
if len(multiple_accidents_drivers) > 0:
    print("There are drivers who have been involved in multiple accidents.")
else:
    print("No driver has been involved in multiple accidents.")

DRIVER NAME
MANIKANDAN       379
MURUGAN          363
UNKNOWN          360
KUMAR            301
SARAVANAN        299
                ...
Nedunchezhian      2
basker             2
Sanmugavel         2
MANIRATHINAM       2
tAMILMANI          2
Name: count, Length: 4595, dtype: int64
There are drivers who have been involved in multiple accidents.

damm, that's quite a reputation to have. I think we can drop the driver name column as well

In [24]:
df = df.drop(columns=['DRIVER NAME'])

In [25]:
df.head()

,DISTRICT,POLICE STATION,DATE,DAY,ACCIDENT TYPE,WEATHER CONDITION,VEHICLE TYPE,COLLITION TYPE,ROAD TYPE,DRIVER AGE,24_HOUR_TIME,24_HOUR_TIME_STR
1,ARIYALUR,ANDIMADAM,2017-01-18,Wednesday,FATAL,FINE,BUS,HEAD ON,STATE HIGHWAY,50,11:30:00,11:30
2,ARIYALUR,ANDIMADAM,2017-01-24,Tuesday,SIMPLE INJURY (HOSPITALISED),FINE,MOTOR CYCLE,HIT PEDESTRIAN,STATE HIGHWAY,30,11:00:00,11:00
3,ARIYALUR,ANDIMADAM,2017-01-15,Sunday,FATAL,FINE,MOPED,HIT FROM REAR,STATE HIGHWAY,30,10:30:00,10:30
4,ARIYALUR,ANDIMADAM,2017-01-26,Thursday,SIMPLE INJURY (HOSPITALISED),FINE,CAR LMV,HIT FROM REAR,STATE HIGHWAY,45,16:15:00,16:15
5,ARIYALUR,ANDIMADAM,2017-02-07,Tuesday,FATAL,FINE,MOTOR CYCLE,HIT PEDESTRIAN,STATE HIGHWAY,35,19:30:00,19:30

We can probably work with just the 24_hour_time and don't need the string either. Let's get rid of that too

In [26]:
df = df.drop(columns = ["24_HOUR_TIME_STR"])

In [27]:
df.head()

,DISTRICT,POLICE STATION,DATE,DAY,ACCIDENT TYPE,WEATHER CONDITION,VEHICLE TYPE,COLLITION TYPE,ROAD TYPE,DRIVER AGE,24_HOUR_TIME
1,ARIYALUR,ANDIMADAM,2017-01-18,Wednesday,FATAL,FINE,BUS,HEAD ON,STATE HIGHWAY,50,11:30:00
2,ARIYALUR,ANDIMADAM,2017-01-24,Tuesday,SIMPLE INJURY (HOSPITALISED),FINE,MOTOR CYCLE,HIT PEDESTRIAN,STATE HIGHWAY,30,11:00:00
3,ARIYALUR,ANDIMADAM,2017-01-15,Sunday,FATAL,FINE,MOPED,HIT FROM REAR,STATE HIGHWAY,30,10:30:00
4,ARIYALUR,ANDIMADAM,2017-01-26,Thursday,SIMPLE INJURY (HOSPITALISED),FINE,CAR LMV,HIT FROM REAR,STATE HIGHWAY,45,16:15:00
5,ARIYALUR,ANDIMADAM,2017-02-07,Tuesday,FATAL,FINE,MOTOR CYCLE,HIT PEDESTRIAN,STATE HIGHWAY,35,19:30:00

In [28]:
df.isna().sum()

DISTRICT             0
POLICE STATION       0
DATE                 0
DAY                  0
ACCIDENT TYPE        0
WEATHER CONDITION    0
VEHICLE TYPE         0
COLLITION TYPE       0
ROAD TYPE            0
DRIVER AGE           0
24_HOUR_TIME         0
dtype: int64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59283 entries, 1 to 62858
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   DISTRICT           59283 non-null  object
 1   POLICE STATION     59283 non-null  object
 2   DATE               59283 non-null  datetime64[ns]
 3   DAY                59283 non-null  object
 4   ACCIDENT TYPE      59283 non-null  object
 5   WEATHER CONDITION  59283 non-null  object
 6   VEHICLE TYPE       59283 non-null  object
 7   COLLITION TYPE     59283 non-null  object
 8   ROAD TYPE          59283 non-null  object
 9   DRIVER AGE         59283 non-null  int64
 10  24_HOUR_TIME       59283 non-null  object
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 5.4+ MB

In [31]:
df["DRIVER AGE"].describe()

count    59283.000000
mean        35.880674
std         11.682171
min         16.000000
25%         27.000000
50%         35.000000
75%         43.000000
max         99.000000
Name: DRIVER AGE, dtype: float64

I'm pretty satisfied with the data now. Let's save this as cleaned data and work with this

In [32]:
df.to_csv("Cleaned_Data.csv", index=False)